# to be used for the DB connection
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
[database]
dialect = "postgresql"
host = "database-2-instance-1.cxyltt2bn4hq.us-east-1.rds.amazonaws.com"
db_name = "nasajaa2"
port = "5432"
user = "postgres"
password = "Inter1986"